service: serverless-python-api

provider:
  name: aws
  runtime: python3.9
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${env:AWS_REGION}
    USERS_TABLE: usersTable

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dynamodb

custom:
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  getUsers:
    handler: src/users/get_users.handler
    events:
      - http:
          path: users
          method: GET

  createUser:
    handler: src/users/create_user.handler
    events:
      - http:
          path: users
          method: post

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
